### ISSUE TITLE
Thumbnail Cache dir is not created automatically anymore

### ISSUE THREAD

**Issue by benjaminpick** [futtta/wp-youtube-lyte#22]
Hi, 
I realized that the cache stopped working (and falling back to the youtube 301-redirection) because each time I clear my caches, it deletes the lyteCache-Folder as well - and it isn't re-created automatically. This seems to come from 

https://github.com/futtta/wp-youtube-lyte/commit/f38e4d15a53bbf50e8c922bc88b7d16fc58aa0cb

It seems to create the folder only if `lyte_filter_local_thumb_doublecheck` is enabled? Can you check that condition please?

(I am using the plugin to implement GDPR restrictions so simply redirecting to YouTube is actually worse than showing an error message or something, then at least I would have realised earlier that it was redirecting... Can I send you a pull request that disables lyte_thumb_fallback() via a filter, similar to `lyte_filter_local_thumb_doublecheck` ?)

**Comment by futtta** [comment]
Just [did a commit](https://github.com/futtta/wp-youtube-lyte/commit/4995f32c5dd972042d183bd0e312bc42295cb1d0) that should ensure the DIR is there, can you test that?

**Comment by benjaminpick** [comment]
Yes it's working now, thank you!

**Comment by futtta** [comment]
you're welcome! :)
