### ISSUE TITLE
double dash in code blocks replaced by unicode dash

### ISSUE THREAD

**Issue by paroj** [futtta/wp-youtube-lyte#25]
wp: 5.7.2
wp-lyte: 1.7.16

seems the fix in 593566ca7df46c9da425b7ba7d24d055ee6cb2fc is incomplete.
Why does this plugin need to do that anyway?

**Comment by futtta** [comment]
historically, don't even remember I'm afraid. but if you want you can use below code snippet to disable it;

`add_filter( 'lyte_kinda_textureize', '__return_false' );`

in the future I might disable it by default too.
