### ISSUE TITLE
Support for "shorts" YouTube video format

### ISSUE THREAD

**Issue by alessandrocarrera** [futtta/wp-youtube-lyte#32]
Currently the plugin not supports the YouTube "shorts" video format. You can see an example of this video format here:

https://www.youtube.com/shorts/RN29WKHeMDs

I think that implementing the support for this video format is simple because you still have the video ID into the URL. Thank you!

**Comment by alessandrocarrera** [comment]
@futtta thank you for your reply. I'm sorry but it not works. I find this link into the output on frontend:

```
httpv://www.youtube.com/watch?v=shorts/RN29WKHeMDs
```

**Comment by futtta** [comment]
still strange, as I did the same thing (add the link in the  editor) and it worked out of the box (even without the code snippet) ... Are you using a pagebuilder (Elementor/ Beaver Builder/ ...) or WordPress blocks (Gutenberg) or the classic editor?

**Comment by alessandrocarrera** [comment]
@futtta I use classic editor. I try again in a Wordpress clean installation and I'll get back to you with more information. Thank you!

**Comment by alessandrocarrera** [comment]
@futtta sorry for my delay. I tested the bug into a Wordpress clean installation with this details:

- WordPress 6.0.2
- Theme Twenty Twenty-Two 1.2
- Plugin Classic Editor 1.6.2
- Plugin WP YouTube Lyte 1.7.19

Everything updated at the last version. I'm still reproducing the problem. I create a new post, paste a lorem ipsum text, after a "shorts" YouTube video link like [this](https://www.youtube.com/shorts/RN29WKHeMDs) and after a lorem ipsum text again. This is the frontend result:

------------------------------

![1](https://user-images.githubusercontent.com/74904794/195362872-38fc9cc0-ebc6-48a1-b55f-687d2a642dff.png)

------------------------------

I have this setting on WP YouTube Lyte:

------------------------------

![2](https://user-images.githubusercontent.com/74904794/195363064-cc25525e-1574-492e-8719-a46a9ece20cf.png)

------------------------------

I tried to fix using a similar solution like your filter into [this reply](https://github.com/futtta/wp-youtube-lyte/issues/32#issuecomment-1273528554) and I resolved the problem with this snippet:

```php
add_filter( 'lyte_content_preparse', 
    function( $in ) {
        return str_replace( 'httpv://www.youtube.com/watch?v=shorts/', 'httpv://www.youtube.com/watch?v=', $in );
    }
);
```

So, I think that into your code flow something do a pre-parse and it breaks the URL. With this filter (using a correct search parameter), I solve the problem and now I have this result:

------------------------------

![3](https://user-images.githubusercontent.com/74904794/195364601-db5eabd1-bd95-4ffb-b9db-99ec60fd5895.png)

------------------------------

Can you check it please and (if this is correct for you), can you release an update of your plugin? Thank you so much! 😊

**Comment by alessandrocarrera** [comment]
@futtta I finally understood the problem! I test your code with a PHP live debugger and I found the exact point where your code generate the URL `httpv://www.youtube.com/watch?v=shorts/RN29WKHeMDs`. So I searched into your github source the same point for showing it to you but when I compare the 2 functions I find some differences! Your `1.7.19` on Github (for the file `wp-youtube-lyte.php`) is different from the `1.7.19` installed from Wordpress marketplace. This is the final DIFF:

https://www.diffchecker.com/aukzFyZM

Finally I did a "crazy monkey test" and I copy the source of the Github `wp-youtube-lyte.php` into my local source of the clean installation of Wordpress and.... magic! It works and I have the same behavior of yours! So please can you synch your Github version with Wordpress marketplace and release it please? It is very important for me. Thank you so much! 😃

PS. I attach a screenshot of the interested part of the diff, too:

![diff](https://user-images.githubusercontent.com/74904794/195788212-9f656412-5bb4-4e0f-b485-977c445a5794.png)

**Comment by futtta** [comment]
argh!! I briefly thought of that but forgot to compare myself. So simple!
I'll push LYTE 1.7.20 out today :-)

**Comment by alessandrocarrera** [comment]
@futtta Perfect! So I await the update! Thank you so much for your kindness 😄

**Comment by futtta** [comment]
released just now :)

thanks for reporting & insisting! :-)

**Comment by alessandrocarrera** [comment]
> released just now :)
> thanks for reporting & insisting! :-)

Good! I am happy to have made my contribution! Thank you, too! 😄
