### ISSUE TITLE
Regex misses figcaption

### ISSUE THREAD

**Issue by thartl** [futtta/wp-youtube-lyte#33]
The regex patterns in lyte_prepare() do not account for css classes core added to figcaption.
Replacing `<figcaption>` in both patterns with `<figcaption.*>` fixes this.

**Comment by futtta** [comment]
feel free to do a pull request @thartl (unless if you prefer me to simply get on with it off course) :-)

**Comment by thartl** [comment]
Okay, done.
Thank you for the quick response and a great plugin :)
