### ISSUE TITLE
Dismiss API key notification

### ISSUE THREAD

**Issue by borjaMarti** [futtta/wp-youtube-lyte#39]
I don't intend on using an API key, but this notification is permanently fixed on all dashboard sections. 

(`function lyte_admin_nag_apikey()`)

Can a dismiss option be added?

I'm not versed in PHP, but I've been looking into the code to see how I'd go about it to make a pull request. Found the function on `options.php`. I think I know how to add the Dismiss button and the conditional logic to not display the message, but I'm a bit lost on how I'd go about saving the option state.

If you point me in the right direction I'll get on it!

**Comment by futtta** [comment]
simply entering `none` in the API key field should be enough @borjaMarti :-)

**Comment by borjaMarti** [comment]
Oh wow, I'd been trying to enter a bogus key by using the Test Key button and it hadn't occured to me to Save Changes ><

Thank you very much for your timely response @futtta, I appreciate your work ^^
