### ISSUE TITLE
Speed up serving of cached thumbs by bypassing PHP

### ISSUE THREAD

**Issue by jan-san** [futtta/wp-youtube-lyte#8]
I just set up the plugin on a site, and found that activating local thumbnails actually slowed down the site, as the response from lyteThumbs.php (with a primed cache) took significantly longer than loading it from YT (even including the connection overhead). The site is on a slow, shared hosting plan.

A way to speed this up could be as follows (for sites with mod_rewrite support):

* local thumbs are requested as `/wp-content/plugins/wp-youtube-lyte/cache/[video-id].jpg`
* add a .htaccess file to /wp-content/plugins/wp-youtube-lyte/cache that either returns the image directly (if the file exists already), or rewrites the the request to lyteThumbs.php

**Comment by futtta** [comment]
afraid assuming .htaccess will work is not an option, we need a solution that works out of the box for everyone, irrespective if they're on Apache (with our without allowoverrides), IIS, nginx, .. :-)

the solution is in the "with a primed cache" part; request the page with the LYTE once to make sure the thumbnail is cached and it _should_ be faster then YT's, not slower.
