### ISSUE TITLE
Disable plugin in feeds

### ISSUE THREAD

**Issue by dillix** [futtta/wp-youtube-lyte#9]
Hi! Is there a way to disable plugin in feeds?

**Comment by futtta** [comment]
maybe try commenting out [line 137 in wp-youtube-lyte.php](https://github.com/futtta/wp-youtube-lyte/blob/master/wp-youtube-lyte.php#L137)?

**Comment by futtta** [comment]
a filter to disable LYTE actiing on feeds was added a couple of months ago, see https://github.com/futtta/wp-youtube-lyte/commit/f740c9c724dad9ee0555ed5a05d88caa388a96e7
